Flask Web App/app/views/manager_views.py
import datetime
from flask import Blueprint, render_template
from flask_user import roles_required

from app.views.error_views import page_not_found
from app.models.bot_models import Bots
from app.common.extensions import cache

manager_blueprint = Blueprint("manager", __name__, template_folder="templates")


@manager_blueprint.route("/manager")
@roles_required("Admin")
# @cache.cached(timeout=50)
def control_panel():
    """Returns a template for the control panel of the manager."""

    query_bots = Bots.query.all()

    return render_template("manager/manager.html", bots_list=query_bots)


@manager_blueprint.route("/manager/train/ind/<bot_name>")
@roles_required("Admin")  # Limits access to users with the 'admin' role
def train_ind_bot(bot_name):
    """Returns a template for training overview for a specific bot."""

    # get bot
    bot = Bots.query.filter_by(bot_name=bot_name).first()

    # if not found
    if not bot:
        return page_not_found("Bot")

    # get current time and pass it to the template

    return render_template("manager/train.html", bot=bot, ind=True)


@manager_blueprint.route("/manager/train/dist/<bot_name>")
@roles_required("Admin")  # Limits access to users with the 'admin' role
def train_dist_bot(bot_name):
    """Returns a template for training overview for a specific bot."""

    bot = Bots.query.filter_by(bot_name=bot_name).first()

    if not bot:
        return page_not_found("Bot")
    return render_template("manager/train.html", bot=bot, ind=False)

Flask Web App/app/templates/manager/manager.html
{% extends "base.html" %}
{% block title %}Manager{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/links.css') }}">
{% endblock %}
{% block content %}
<h1 class="text-center">Bots Manager</h1>
  {% if not bots_list %}
  <h3>No bots currently exist.</h3>
  {% endif %}
  <div class="row mt-5 justify-content-center">
    {% for bot in bots_list %}
    <div class="card mb-4 m-3" style="width: 18rem;padding: 10px;">
        <div class="card-body">
            <div class="text-center">
              <h5 class="card-title text-center">{{bot.bot_name}}</h5>
            </div>
            <h6 class="card-subtitle mb-2 text-muted">Added at: {{bot.bot_added_at}}</h6>
            <p class="card-text">{{bot.bot_description}}</p>
            <hr>
            <div class="button-container text-center">
              <a  class="draw-outline btn-manager" href={{ url_for('manager.train_ind_bot', bot_name=bot.bot_name) }}>{%trans%}Train Individually{%endtrans%}</a>
              <a  class="draw-outline btn-manager" href={{ url_for('manager.train_dist_bot', bot_name=bot.bot_name) }}>{%trans%}Train Distributed{%endtrans%}</a>
            </div>
        </div>
    </div>
    {% endfor %}

  </div>
{% endblock %}

Flask Web App/app/templates/manager/train.html
{% extends "base.html" %}
{% block title %}Train {{bot_name}}{% endblock %}
{% block head %}
  {{ super() }}
{% endblock %}
{% block content %}
  {% if ind == True %}
  <h1 class="text-center">Training {{bot.bot_name}} Individually</h1>
  {% else %}
  <h1 class="text-center">Training {{bot.bot_name}} Distributively</h1>
  {% endif %}

<div class="container-fluid">
  <div id="timeDiv">
    <div id="startTime">
    </div>
    <div id="endTime">
    </div>
  </div>
</div>

  {% block train %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/train.js') }}"></script>
  {% endblock %}
  <script>
    run_training_update();
  </script>


{% endblock %}