Flask Web App/app/views/bot_views.py
from flask import Blueprint, render_template
from flask import request
from flask_user import login_required, roles_required
from flask import Response

from app.models.bot_models import Bots, Statistics

from app.views.error_views import page_not_found
from app.util.util import check_if_bot_exists
from pygtail import Pygtail
import time
import logging

bot_blueprint = Blueprint("bot", __name__, template_folder="templates")
log = logging.getLogger(__name__)

LOG_FILE = "logs/Art Chatbot.log"


@bot_blueprint.route("/bots")
def show_all_bots():
    """Returns a template for the show_all_bots page."""
    bots_list = []

    for qbot in Bots.query.all():
        bots_list.append(qbot)

    return render_template("bots/bots.html", bots_list=bots_list)


@bot_blueprint.route("/logs/<bot_name>")
@roles_required("Admin")  # Limits access to users with the 'admin' role
def show_logs(bot_name):
    """Returns a template for logs overview for a specific bot."""
    if not check_if_bot_exists(bot_name):
        return page_not_found(bot_name)

    bot = Bots.query.filter_by(bot_name=bot_name).first()

    return render_template("bots/logs.html", bot=bot)


@bot_blueprint.route("/")
def entry_point():
    return render_template("bots/logs.html")


@bot_blueprint.route("/progress")
def progress():
    def generate():
        x = 0
        while x <= 100:
            yield "data:" + str(x) + "\n\n"
            x = x + 10
            time.sleep(0.5)

    return Response(generate(), mimetype="text/event-stream")


@bot_blueprint.route("/log")
def progress_log():
    def generate():
        for line in Pygtail(LOG_FILE, every_n=1):
            yield "data:" + str(line) + "\n\n"
            time.sleep(1)

    return Response(generate(), mimetype="text/event-stream")


@bot_blueprint.route("/env")
def show_env():
    env = {}
    for k, v in request.environ.items():
        env[k] = str(v)
    return env


@bot_blueprint.route("/conversations/<bot_name>")
@login_required  # Limits access to authenticated users
def show_all_conversations(bot_name):
    """Returns a template for conversations overview for a specific bot."""
    if not check_if_bot_exists(bot_name):
        return page_not_found(bot_name)

    return render_template("bots/conversations.html", bot_name=bot_name)


@bot_blueprint.route("/statistics/all")
@login_required  # Limits access to authenticated users
def show_statistics_for_all():
    """Returns a template for conversations overview for a specific bot."""

    # get all bots from db
    bots_list = Bots.query.all()

    weekday_code_dict = {
        0: "Mon",
        1: "Tue",
        2: "Wed",
        3: "Thu",
        4: "Fri",
        5: "Sat",
        6: "Sun",
    }
    bot_data = []
    bot_labels = []
    # get past seven days of stats data for a bot
    if not bots_list:
        log.critical("No bots in DB, function cannot proceed.")
    for bot in bots_list:
        stats_objs = Statistics.retrieve_past_week(bot_id=bot.id)
        if stats_objs:
            temp_list_data = []
            temp_list_labels = []
            for stats in stats_objs:
                temp_list_data.append(stats.num_requests_handled)
                date = stats.date_added
                weekday_verbose = weekday_code_dict[stats.date_added.weekday()]
                label_temp = f"{weekday_verbose}, {date.day}.{date.month}.{date.year}"
                temp_list_labels.append(label_temp)
            bot_data.append(temp_list_data)
            bot_labels.append(temp_list_labels)
            log.info(
                f"Statistics object for bot: {bot.bot_name}, with id: {bot.id} found!"
            )
        else:
            log.warn(
                f"Statistics object for bot: {bot.bot_name}, with id: {bot.id} not found!"
            )
            pass
    return render_template(
        "bots/stats_all.html", data=bot_data, labels=bot_labels, bots_list=bots_list
    )


@bot_blueprint.route("/statistics/<bot_name>")
def show_statistics_for_bot(bot_name):
    """Returns a template for conversations overview for a specific bot."""
    if not check_if_bot_exists(bot_name):
        return page_not_found(bot_name)

    # retrieve bot information from db
    bot = Bots.query.filter_by(bot_name=bot_name).first()
    stats = Statistics.query.filter_by(bot_id=bot.id).all()

    return render_template("bots/stats_bot.html", stats=stats)

Flask Web App/app/views/main_views.py
import os
from flask import Blueprint, redirect, render_template
from flask import request, url_for
from flask_user import current_user, login_required, roles_required

from app import db

from app.models.site_models import Site
from app.common.extensions import cache
from app.views.error_views import page_not_found

main_blueprint = Blueprint("main", __name__, template_folder="templates")


@main_blueprint.route("/")
@cache.cached(timeout=50)
def index():
    """Returns a template for the index page."""

    query_site = Site.query.filter(
        Site.site_name == os.getenv("INIT_SITE_NAME")
    ).first()
    if query_site:
        query_site.site_visitors_total_count += 1
        db.session.commit()

        return render_template("site/index.html", site_data=query_site)
    else:
        return page_not_found("Site")


@main_blueprint.route("/member")
@login_required  # Limits access to authenticated users
@cache.cached(timeout=50)
def member_page():
    user = current_user

    context = {
        "user": user,
    }
    return render_template("user/user_profile_page.html", context=context)


@main_blueprint.before_app_request
def before_request():
    # lang = get_locale()
    # lang = lang if lang else app.config['BABEL_DEFAULT_LOCALE']
    # set_lang(lang)

    if request.path.startswith("/admin"):
        if current_user.is_authenticated:
            if not current_user.has_role("Admin"):
                return redirect(url_for("user.logout"))
        else:
            return redirect(url_for("user.login"))


# @main_blueprint.route('/profile', methods=['GET', 'POST'])
# @login_required
# def user_profile_page():
#     # Initialize form
#     form = UserProfileForm(request.form, obj=current_user)

#     # Process valid POST
#     if request.method == 'POST' and form.validate():
#         # Copy form fields to user_profile fields
#         form.populate_obj(current_user)

#         # Save user_profile
#         db.session.commit()

#         # Redirect to home page
#         return redirect(url_for('main.index'))

#     # Process GET or invalid POST
#     return render_template('user/user_profile_page.html',
#                            form=form)

Flask Web App/app/views/manager_views.py
import datetime
from flask import Blueprint, render_template
from flask_user import roles_required

from app.views.error_views import page_not_found
from app.models.bot_models import Bots
from app.common.extensions import cache

manager_blueprint = Blueprint("manager", __name__, template_folder="templates")


@manager_blueprint.route("/manager")
@roles_required("Admin")
# @cache.cached(timeout=50)
def control_panel():
    """Returns a template for the control panel of the manager."""

    query_bots = Bots.query.all()

    return render_template("manager/manager.html", bots_list=query_bots)


@manager_blueprint.route("/manager/train/ind/<bot_name>")
@roles_required("Admin")  # Limits access to users with the 'admin' role
def train_ind_bot(bot_name):
    """Returns a template for training overview for a specific bot."""

    # get bot
    bot = Bots.query.filter_by(bot_name=bot_name).first()

    # if not found
    if not bot:
        return page_not_found("Bot")

    # get current time and pass it to the template

    return render_template("manager/train.html", bot=bot, ind=True)


@manager_blueprint.route("/manager/train/dist/<bot_name>")
@roles_required("Admin")  # Limits access to users with the 'admin' role
def train_dist_bot(bot_name):
    """Returns a template for training overview for a specific bot."""

    bot = Bots.query.filter_by(bot_name=bot_name).first()

    if not bot:
        return page_not_found("Bot")
    return render_template("manager/train.html", bot=bot, ind=False)

Flask Web App/app/templates/base.html
<!doctype html>
<html>
  <head>
    <title>{% block title %}{% endblock %} - Raysa</title>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
    <meta content="utf-8" http-equiv="encoding" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@300&display=swap" rel="stylesheet">
    <!--Import Google Icon Font-->
    <link
        href="https://fonts.googleapis.com/icon?family=Material+Icons"
        rel="stylesheet"
    />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap"
        rel="stylesheet"
    />
    <link
        href="https://fonts.googleapis.com/css?family=Raleway:500&display=swap"
        rel="stylesheet"
    />

    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap"
        rel="stylesheet"
    />

    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
        href="https://fonts.googleapis.com/css2?family=Lato&display=swap"
        rel="stylesheet"
    />



    <!-- Remix Icons package -->
	  <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css'>
    <!--Bootstrap css-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--Chat css-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/chat.css') }}">
    <!-- <link rel="stylesheet" href="static/css/home.css"> -->
    <!--Import Font Awesome Icon Font-->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
      integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0="
      crossorigin="anonymous"
    />
    <!--Main css-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <!--Additional scripts-->
    {% block head %}{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>

    <!-- START NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-custom fixed-top ml-auto">
      <div class="container-fluid">

        <div class="navbar-header align-middle">
          <a class="navbar-brand" href="{{ url_for('main.index') }}">
            <img src="{{ url_for('static', filename='img/botAvatar.png') }}" id="brandLogo" alt="logo">
              Raysa
          </a>
        </div>

          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{{ url_for('main.index') }}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('admin.index') }}">Backend</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('main.member_page') }}">Member Page</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('bot.show_all_bots') }}">Bots</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('bot.show_statistics_for_all') }}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Statistics
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{{ url_for('manager.control_panel') }}">Manager</a>
                </li>

              </ul>

              <ul class="navbar-nav ms-auto">
                {% if not user.is_authenticated %}
                <li class="nav-item">
                  <a href="{{ url_for('user.login')}}" class="nav-link">
                  <span class="ri-login-circle-line ri-xl align-middle"></span>
                  </a>
                </li>

                {% else %}
                <li class="nav-item">
                  <a href="{{ url_for('user.logout')}}" class="nav-link">
                    <span class="ri-logout-circle-line ri-xl align-middle"></span>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{{ url_for('main.member_page')}}" class="nav-link">
                    <span class="span-name align-middle">{{user.first_name}} {{user.last_name}}</span>
                    <span class="ri-account-circle-line ri-xl align-middle"></span>
                  </a>
                </li>

                {% endif %}
              </ul>
            </div>
        </div>
    </nav>
    <!-- END NAVBAR -->
    <div class="m-5" id="wrap">
      <div id="main" class="container clear-top">
      {% block content %}{% endblock %}
      </div>
    </div>
    <!-- Footer -->
    <div class="fixed-bottom" id="footer">
      {% block footer %}
      &copy; Copyright 2021-2022 by <a href="https://www.galaktoza.de">Svetozar Stojanovic</a>.
      {% endblock %}
    </div>
    <!-- Chat widget -->
    <div class="chat-bar-collapsible widget-z-index">
        <button id="chat-button" type="button" class="collapsible">Try me out!
            <i id="chat-icon" style="color: #fff;" class="fa fa-fw fa-comments-o"></i>
        </button>
        <div class="content">
          <div class="full-chat-block">
              <!-- Message Container -->
              <div class="outer-container">
                  <div class="chat-container">
                      <!-- Messages -->
                      <div id="chatbox">
                          <h5 id="chat-timestamp"></h5>
                          <p id="botStarterMessage" class="botText"><span>Loading...</span></p>
                      </div>

                      <!-- User input box -->
                      <div class="chat-bar-input-block">
                          <div id="userInput">
                              <input id="textInput" class="input-box" type="text" name="msg"
                                  placeholder="Tap 'Enter' to send a message">
                              <p></p>
                          </div>

                          <div class="chat-bar-icons">
                              <i id="chat-icon" style="color: #333;" class="fa fa-fw fa-send"
                                  onclick="sendButton()"></i>
                          </div>
                      </div>

                      <div id="chat-bar-bottom">
                          <p></p>
                      </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
    <!-- Bootstrap JS Bundle -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/responses.js') }}"></script>
    <script src="{{ url_for('static', filename='js/chat.js') }}"></script>
    {% block train %}
    {% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    {% block scripts %}
    {% endblock %}
  </body>
</html>

Flask Web App/app/templates/user_page.html
{% extends "base.html" %} 

{% block content %}
    <h2>{{context.user.first_name}} {{context.user.last_name}}</h2>
    <img alt="No gravatar present" src="{{ context.user.email | gravatar }}">
    <p><a href={{ url_for('user.register') }}>{%trans%}Register{%endtrans%}</a></p>
    <p><a href={{ url_for('user.login') }}>{%trans%}Sign in{%endtrans%}</a></p>
    <p><a href={{ url_for('main.index') }}>{%trans%}Home Page{%endtrans%}</a> (accessible to anyone)</p>
    <p><a href={{ url_for('main.member_page') }}>{%trans%}Member Page{%endtrans%}</a> (login_required: member@example.com / Password1)</p>
    <p><a href={{ url_for('main.admin_page') }}>{%trans%}Admin Page{%endtrans%}</a> (roles_required: admin@example.com / Password1)</p>
    <p><a href={{ url_for('user.logout') }}>{%trans%}Sign out{%endtrans%}</a></p>
{% endblock %}

Flask Web App/app/templates/user_profile_page.html
{% extends "base.html" %}

{% block content %}
<h1>User Profile</h1>

<p><a href="{{ url_for('user.change_password') }}">Change password</a></p>

{% from "common/form_macros.html" import render_field, render_submit_field %}
<form action="" method="POST" class="form" role="form">
  <div class="row">
    <div class="col-sm-6 col-md-5 col-lg-4">
    {{ form.hidden_tag() }}

    {{ render_field(form.first_name, tabindex=240) }}

    {{ render_field(form.last_name, tabindex=250) }}

    {{ render_submit_field(form.submit, tabindex=280) }}
    </div>
  </div>
</form>

{% endblock %}